name: Configure Production Certificates

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/config-certs-production.yml'
      - 'ops/playbook/inventory/production'
      - 'ops/playbook/certs-backend.yaml'
      - 'ops/playbook/certs-frontend.yaml'
      - 'ops/playbook/inventory/.trigger-cert-production'

jobs:
  config-certs-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying application
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: ./ops/playbook/certs-frontend.yaml
          inventoryFile: ./ops/playbook/inventory/production
          keyFile: ./ops/ssh/prod_deploy_private_key
          keyFileVaultPass: ${{ secrets.ANSIBLE_VAULT_SECRET }}
          extraVars: "-e domain_name=portal.silverthatch.org.ky -e web_server_ssl_dir_owner=root"
          extraFile: ./ops/playbook/vars/certs.yaml
          verbosity: "vv"

  config-certs-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying application
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: ./ops/playbook/certs-backend.yaml
          inventoryFile: ./ops/playbook/inventory/production
          keyFile: ./ops/ssh/prod_deploy_private_key
          keyFileVaultPass: ${{ secrets.ANSIBLE_VAULT_SECRET }}
          extraVars: "-e domain_name=api.portal.silverthatch.org.ky -e web_server_ssl_dir_owner=www-data"
          extraFile: ./ops/playbook/vars/certs.yaml
          verbosity: "vv"

